//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-OK
        ///AWOL
        ///Aaronic
        ///Aaronical
        ///Abbevillian
        ///Aberdeen
        ///Abyssinian
        ///Acadian
        ///Accadian
        ///Achaean
        ///Acheulean
        ///Acheulian
        ///Achillean
        ///Adam
        ///Adamic
        ///Adamitic
        ///Adamitical
        ///Adonic
        ///Adriatic
        ///Aegean
        ///Aeneolithic
        ///Aeolic
        ///Aesculapian
        ///Afric
        ///African
        ///Afro-American
        ///Afro-Asian
        ///Akkadian
        ///Alabaman
        ///Alabamian
        ///Alaskan
        ///Albanian
        ///Albigensian
        ///Alcaic
        ///Alcibiadean
        ///Aldine
        ///Alemannic
        ///Alexandrian
        ///Algerian
        ///Algonkian
        ///Algonkin
        ///Algonquian
        ///Algonquin
        ///Alhambresque
        ///Alice-in-Wonderland
        ///Alsatian
        ///Altaic
        ///American
        ///Amerindian
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Adjetives {
            get {
                return ResourceManager.GetString("Adjetives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;tween
        ///&apos;tween-decks
        ///Byronically
        ///Christian
        ///Christianly
        ///Fridays
        ///Gallice
        ///Germanically
        ///Hebraically
        ///Jacobinically
        ///Jesuitically
        ///Jewishly
        ///Judaically
        ///Judaistically
        ///Malaprop
        ///Mondays
        ///OK&apos;d
        ///Romeward
        ///Saturdays
        ///Socratically
        ///Somerville
        ///Sundays
        ///Thursdays
        ///Tuesdays
        ///Whiggishly
        ///aback
        ///abaft
        ///abandonedly
        ///abashedly
        ///abeam
        ///abed
        ///abhorrently
        ///abidingly
        ///abiogenetically
        ///abjectly
        ///ablaze
        ///ablins
        ///abloom
        ///ably
        ///abnormally
        ///aboard
        ///abominably
        ///aboriginally
        ///aborning
        ///abortively
        ///about
        ///above
        ///above-board
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Adverbs {
            get {
                return ResourceManager.GetString("Adverbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-bomb
        ///A-bombs
        ///A-frame
        ///ABC
        ///Aachen
        ///Aarhus
        ///Aaron
        ///Abadan
        ///Abaddon
        ///Abbasid
        ///Abbasids
        ///Abbevillian
        ///Abbotsford
        ///Abbott
        ///Abby
        ///Abdul
        ///Abe
        ///Abednego
        ///Abel
        ///Abelard
        ///Aberdare
        ///Aberdeen
        ///Aberdeenshire
        ///Aberystwyth
        ///Abib
        ///Abidjan
        ///Abingdon
        ///Abraham
        ///Abrahams
        ///Absalom
        ///Abydos
        ///Abyssinia
        ///Abyssinian
        ///Abyssinians
        ///Acadia
        ///Acadian
        ///Acadians
        ///Acapulco
        ///Accadian
        ///Accra
        ///Accrington
        ///Achaea
        ///Achaean
        ///Achaeans
        ///Achates
        ///Achernar
        ///Acheron
        ///Acheson
        ///Acheulian
        ///Achilles
        ///Achitophel
        ///Acis
        ///Acol
        ///Acrilan
        ///Actaeon
        ///Actium
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Nouns {
            get {
                return ResourceManager.GetString("Nouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Africanize
        ///Africanized
        ///Africanizes
        ///Africanizing
        ///Americanise
        ///Americanize
        ///Americanized
        ///Americanizes
        ///Americanizing
        ///Aryanise
        ///Aryanised
        ///Aryanises
        ///Aryanising
        ///Aryanize
        ///Aryanized
        ///Aryanizes
        ///Aryanizing
        ///Atticise
        ///Atticised
        ///Atticises
        ///Atticising
        ///Atticize
        ///Atticized
        ///Atticizes
        ///Atticizing
        ///Balkanise
        ///Balkanised
        ///Balkanises
        ///Balkanising
        ///Braille
        ///Christianise
        ///Christianised
        ///Christianises
        ///Christianising
        ///Christianize
        ///Christianized
        ///Christianizes
        ///Christianizing
        ///English
        ///French-polish
        ///French-polishe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Verbs {
            get {
                return ResourceManager.GetString("Verbs", resourceCulture);
            }
        }
    }
}
